---
title: "db_push"
format: html
editor: source
---

## Load Packages

```{r}

if(!require(librarian)){
  install.packages(librarian)
  library(librarian)
}

shelf(tidyverse, here, DBI, RPostgres)

```


## read all_qpcr table
```{r}

qpcr_bd_results <- read_csv(here("final_qpcr", "merged_qpcr.csv"))

```


## connect to DB
```{r}


#| output: false
tryCatch({
    drv <- dbDriver("Postgres")
    print("Connecting to Database…")
    connection <- dbConnect(drv,
                       dbname = Sys.getenv("aws_dbname"),
                       host = Sys.getenv("aws_host"),
                       port = Sys.getenv("aws_port"),
                       user = Sys.getenv("aws_user"),
                       password = Sys.getenv("aws_password"),
                       timezone=NULL)
    print("Database Connected!")
    },
    error=function(cond) {
            print("Unable to connect to Database.")
    })


dbExecute(connection, "set search_path = 'survey_data';")



```

## Write table to DB
```{r}

dbWriteTable(connection, 'qpcr_bd_results', qpcr_bd_results, overwrite = T)



```

