---
title: "legacy_panama_qpcr_wrangling"
format: html
editor: visual
---

## Load Packages

```{r}

if(!require(librarian)){
  install.packages(librarian)
  library(librarian)
}

shelf(tidyverse, here, DBI, RPostgres, janitor, readxl)

```

## Read in all .xlxs files

```{r}

file_list <- gsub("\\.xlsx$","", list.files(here("data")))


for (i in file_list){
  
  assign(i, read_excel(here("data", paste(i, ".xlsx", sep=""))))
  
}


```

Columns:

## Atelopus

```{r}

clean_atelopus <- atelopus %>% 
  clean_names() %>% 
  select(!c(sample_type, site, species, home_base, preservative, notes_7, status, 
            location_of_sample)) %>% 
  rename(comments = notes_19,
         bd_swab_id = frog_id,
         average_zoospores = swab_result,
         average_copy_number = quantity) %>% 
  mutate(extraction_kit = str_to_lower(str_replace_all(extraction_kit, " ", "_")),
         ct = if_else(is.na(ct), 0, ct),
         average_copy_number = if_else(is.na(average_copy_number), 0, average_copy_number),
         average_zoospores = if_else(is.na(average_zoospores), 0, average_zoospores),
         bd_swab_id = str_to_lower(str_replace_all(bd_swab_id, "-", "_")),
         standard = "pisces",
         extraction_kit = "bioline",
         result = if_else(result == "positive", "p", result),
         result = if_else(result == "negative", "n", result))


```

## fall_2012 - extraction kit?

```{r}

clean_fall_2012 <- fall_2012 %>% 
  clean_names() %>% 
  select(!c(site, species)) %>% 
  rename(comments = notes,
         bd_swab_id = swab,
         extraction_plate_id = extraction_plate,
         pcr_plate_id = pcr_plate) %>% 
  mutate(bd_swab_id = str_replace_all(bd_swab_id, "-", "_"),
         average_zoospores = if_else(is.na(average_zoospores), 0, average_zoospores),
         bd_swab_id = str_remove_all(bd_swab_id, "\\*"),
         standard = "hyatt zoospore-based",
         extraction_kit = "taqman")
  

```

## qpcr_2014

```{r}

clean_2014 <- qpcr_2014 %>% 
  clean_names() %>% 
  select(!c(site, species)) %>% 
  rename(bd_swab_id = id,
         average_zoospores = swab_result,
         comments = additional_notes,
         pcr_plate_id = pcr_plate,
         extraction_plate_id = extraction_plate,
         ct = ct_vlues) %>% 
  mutate(result = if_else(result == "0", "n,n,n", result),
         bd_swab_id = str_to_lower(str_replace_all(bd_swab_id, "-", "_")),
         ct = if_else(is.na(ct), 0, ct),
         average_copy_number = if_else(is.na(average_copy_number), 0, average_copy_number),
         average_zoospores = if_else(is.na(average_zoospores), 0, average_zoospores),
         standard = "pisces",
         extraction_kit = "taqman")

```

## winter_2013

```{r}

clean_winter_2013 <- winter_2013 %>% 
  clean_names() %>% 
  select(!c(site, species)) %>% 
  rename(bd_swab_id = swab,
         average_zoospores = swab_result,
         comments = additional_notes,
         pcr_plate_id = pcr_plate,
         extraction_plate_id = extraction_plate,
         ct = ct_vlues) %>% 
  mutate(ct = if_else(is.na(ct), 0, ct),
         average_copy_number = if_else(is.na(average_copy_number), 0, average_copy_number),
         average_zoospores = if_else(is.na(average_zoospores), 0, average_zoospores),
          bd_swab_id = str_to_lower(str_replace_all(bd_swab_id, "-", "_")),
         standard = "pisces",
         extraction_kit = "taqman")

```

## summer_2013
```{r}

clean_summer_2013 <- summer_2013 %>% 
  clean_names() %>% 
  select(!c(site, species, location)) %>% 
  rename(bd_swab_id = swab,
         average_zoospores = swab_result,
         comments = additional_notes,
         pcr_plate_id = pcr_plate,
         extraction_plate_id = extraction_plate,
         ct = ct_number) %>% 
  mutate(ct = if_else(is.na(ct), 0, ct),
         average_copy_number = if_else(is.na(average_copy_number), 0, average_copy_number),
         average_zoospores = if_else(is.na(average_zoospores), 0, average_zoospores),
          bd_swab_id = str_to_lower(str_replace_all(bd_swab_id, "-", "_")),
         standard = "pisces",
         extraction_kit = "taqman")

```


## qpcr_2015

```{r}

clean_2015 <- qpcr_2015 %>% 
  clean_names() %>% 
  select(!c(site, species)) %>% 
  rename(bd_swab_id = frog_id,
         average_zoospores = swab_result,
         comments = additional_notes,
         ct = mean_ct_value,
         average_copy_number = mean_copy_number) %>% 
  mutate(ct = if_else(is.na(ct), 0, ct),
         average_copy_number = if_else(is.na(average_copy_number), 0, average_copy_number),
         average_zoospores = if_else(is.na(average_zoospores), 0, average_zoospores),
         result = if_else(result == "0", "n,n,n", result),
         bd_swab_id = str_to_lower(str_replace_all(bd_swab_id, "-", "_")),
         standard = "pisces",
         extraction_kit = "taqman")
  

```

## qpcr_2016

```{r}

clean_2016 <- qpcr_2016 %>% 
  clean_names() %>% 
  select(!c(site, species)) %>% 
  rename(bd_swab_id = frog_id,
         average_zoospores = swab_result,
         comments = additional_notes,
         ct = mean_ct_value,
         average_copy_number = mean_copy_number)%>% 
  mutate(ct = if_else(is.na(ct), 0, ct),
         average_copy_number = if_else(is.na(average_copy_number), 0, average_copy_number),
         average_zoospores = if_else(is.na(average_zoospores), 0, average_zoospores),
         result = if_else(result == "0", "n,n,n", result),
         bd_swab_id = str_to_lower(str_replace_all(bd_swab_id, "-", "_")),
         standard = "pisces",
         extraction_kit = "bioline")


```

## Bind all tables together

```{r}

panama_qpcr <- plyr::rbind.fill(clean_2014, clean_2015, clean_2016, clean_atelopus, clean_fall_2012, clean_winter_2013, clean_summer_2013)

write_csv(panama_qpcr, here("data_csv", "panama_qpcr.csv"))

```

## find missing IDs still

```{r}

all_ids <- read_csv(here("data_csv", "2012_2017_bdswab_search_clz.csv"))

missing_ids <- all_ids %>% 
  anti_join(panama_qpcr, by = c("bd_swab_id"))

write_csv(missing_ids, here("data_csv", "remaining_missing_ids.csv"))



```
